export  { default as background } from './background.jpg'
export {  default as titleBanner } from './title-banner.png'
export {  default as startGame } from './startgame.png'
export {  default as student } from './student.png'
export {  default as signIn } from './signin.png'
export {  default as setting } from './setting.png'
export  { default as aboutUs } from './aboutus.png'
export { default as loginButton } from './loginbutton.png'
export { default as signout } from './signout.png'
export { default as popupLogin } from './popup-login1.png'
export { default as loginEnter } from './loginenter.png'

